
# I. Set up input data

library(session)
library(knitr)
library(caret)
library(reshape)
library(Hmisc)
library(ggplot2)
library(gridExtra)
library(limma)
library(edgeR)
library(reshape)
library(DESeq2)
library(tidyr)
library(kableExtra)
library(dplyr)
library(plyr)
library(sva)
library(compareGroups)
library(expss)
library(VennDiagram)
library(RUVSeq)
library(org.Hs.eg.db)
library(clusterProfiler)
library(AnnotationDbi)
library(GO.db)
library(DOSE)
library(pathview)
library("BiocParallel")
library(mixOmics)
library(DaMiRseq)
library(EDASeq)
library(enrichplot)
library(GOSemSim)
library(ReactomePA)

library(survival)
library(survminer)
library(doParallel)
library(foreach)
library(doSNOW)
library(magrittr)
## registry cores to cluster
#cl <- makeCluster(12,type='SOCK')

